version: '3.8'

services:
  web:
    build: .
    command: ["poetry", "run", "python", "JEWELLERY1/manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      